In [22]:
import pandas as pd
from pprint import pprint as pp
import datetime as dt
from sklearn import preprocessing

In [2]:
df = pd.read_csv("../data/2019_averages.csv")

In [3]:
df.head()

,season,week,gameDate,gameTimeEastern,homeNickname,visitorNickname,siteId,siteCity,siteState,roofType,...,VpuntReturnsTouchdowns,VreceivingReceptions,VreceivingTouchdowns,VreceivingLong,VreceivingYards,VreceivingFumbles,VrecevingAverageYards,VtotalTurnovers,VtotalPointsScored,VtimeOfPossSeconds
0,2019.0,1.0,9/5/19,20:20:00,Bears,Packers,4620.0,Chicago,IL,OUTDOOR,...,0.0125,22.8375,1.9875,45.5250,273.8625,0.1625,12.14000,1.2500,24.5750,1827.3125
1,2019.0,1.0,9/8/19,13:00:00,Panthers,Rams,1769.0,Charlotte,NC,OUTDOOR,...,0.0250,19.0000,1.1375,37.7875,210.4750,0.2000,11.40750,1.4250,18.0875,1740.0500
2,2019.0,1.0,9/8/19,13:00:00,Eagles,Redskins,2769.0,Philadelphia,PA,OUTDOOR,...,0.0125,21.8750,1.4125,42.3125,255.2750,0.3375,11.74250,1.6375,20.6750,1804.4750
3,2019.0,1.0,9/8/19,13:00:00,Jets,Bills,3757.0,East Rutherford,NJ,OUTDOOR,...,0.0000,19.1000,1.2000,37.5250,210.5875,0.3000,11.17500,1.7875,18.6875,1764.4125
4,2019.0,1.0,9/8/19,13:00:00,Vikings,Falcons,1652.0,Minneapolis,MN,INDOOR,...,0.0000,24.6000,1.7625,42.4375,279.5000,0.2250,11.61625,1.4000,23.5375,1830.3875

In [6]:
mapping_dictionary = {
    '49ers': 1,
    'Bears': 2,
    'Bengals': 3,
    'Bills': 4,
    'Broncos': 5,
    'Browns': 6,
    'Buccaneers': 7,
    'Cardinals': 8,
    'Chargers': 9,
    'Chiefs': 10,
    'Colts': 11,
    'Cowboys': 12,
    'Dolphins': 13,
    'Eagles': 14,
    'Falcons': 15,
    'Giants': 16,
    'Jaguars': 17,
    'Jets': 18,
    'Lions': 19,
    'Packers': 20,
    'Panthers': 21,
    'Patriots': 22,
    'Raiders': 23,
    'Rams': 24,
    'Ravens': 25,
    'Redskins': 26,
    'Saints': 27,
    'Seahawks': 28,
    'Steelers': 29,
    'Texans': 30,
    'Titans': 31,
    'Vikings': 32,
    'INDOOR': 1,
    'OUTDOOR': 2,
    'RETRACTABLE': 3,
    'Arlington': 1,
    'Atlanta': 2,
    'Baltimore': 3,
    'Carson': 4,
    'Charlotte': 5,
    'Chicago': 6,
    'Cincinnati': 7,
    'Cleveland': 8,
    'Denver': 9,
    'Detroit': 10,
    'East Rutherford': 11,
    'Foxborough': 12,
    'Glendale': 13,
    'Green Bay': 14,
    'Houston': 15,
    'Indianapolis': 16,
    'Jacksonville': 17,
    'Kansas City': 18,
    'Landover': 19,
    'London': 20,
    'Los Angeles': 21,
    'Mexico City': 22,
    'Miami Gardens': 23,
    'Minneapolis': 24,
    'Nashville': 25,
    'New Orleans': 26,
    'Oakland': 27,
    'Opa Locka': 28,
    'Orchard Park': 29,
    'Philadelphia': 30,
    'Pittsburgh': 31,
    'San Diego': 32,
    'San Francisco': 33,
    'Santa Clara': 34,
    'Seattle': 35,
    'St. Louis': 36,
    'St.Louis': 37,
    'Tampa': 38,
    'Toronto': 39,
    'Twickenham': 40,
    None: 23,
    'AZ': 12,
    'CA': 15,
    'CO': 21,
    'FL': 3,
    'GA': 2,
    'IL': 20,
    'IN': 5,
    'LA': 4,
    'MA': 14,
    'MD': 7,
    'MI': 16,
    'MN': 22,
    'MO': 18,
    'NC': 8,
    'NJ': 11,
    'NY': 19,
    'OH': 9,
    'ON': 24,
    'PA': 1,
    'TN': 17,
    'TX': 6,
    'WA': 10,
    'WI': 13,
    '12:30:00': 8,
    '13:00:00': 2,
    '16:05:00': 7,
    '16:15:00': 3,
    '16:25:00': 12,
    '16:30:00': 18,
    '19:00:00': 5,
    '19:10:00': 13,
    '19:20:00': 10,
    '19:30:00': 9,
    '20:00:00': 11,
    '20:15:00': 20,
    '20:20:00': 4,
    '20:25:00': 15,
    '20:30:00': 1,
    '20:40:00': 16,
    '22:15:00': 6,
    '22:20:00': 14,
    '23:35:00': 17,
    '9:30:00': 19
}

In [8]:
df_mapped = df.replace(mapping_dictionary)

In [9]:
df_mapped

,season,week,gameDate,gameTimeEastern,homeNickname,visitorNickname,siteId,siteCity,siteState,roofType,...,VpuntReturnsTouchdowns,VreceivingReceptions,VreceivingTouchdowns,VreceivingLong,VreceivingYards,VreceivingFumbles,VrecevingAverageYards,VtotalTurnovers,VtotalPointsScored,VtimeOfPossSeconds
0,2019.0,1.0,9/5/19,4,2,20,4620.0,6,20,2,...,0.0125,22.8375,1.9875,45.5250,273.8625,0.1625,12.14000,1.2500,24.5750,1827.3125
1,2019.0,1.0,9/8/19,2,21,24,1769.0,5,8,2,...,0.0250,19.0000,1.1375,37.7875,210.4750,0.2000,11.40750,1.4250,18.0875,1740.0500
2,2019.0,1.0,9/8/19,2,14,26,2769.0,30,1,2,...,0.0125,21.8750,1.4125,42.3125,255.2750,0.3375,11.74250,1.6375,20.6750,1804.4750
3,2019.0,1.0,9/8/19,2,18,4,3757.0,11,11,2,...,0.0000,19.1000,1.2000,37.5250,210.5875,0.3000,11.17500,1.7875,18.6875,1764.4125
4,2019.0,1.0,9/8/19,2,32,15,1652.0,24,22,1,...,0.0000,24.6000,1.7625,42.4375,279.5000,0.2250,11.61625,1.4000,23.5375,1830.3875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,2019.0,17.0,12/29/19,2,4,18,3770.0,29,19,2,...,0.0125,17.9500,0.9500,36.2375,206.1625,0.1625,11.61500,1.7375,18.8250,1825.2125
252,2019.0,17.0,12/29/19,2,21,27,1769.0,5,8,2,...,0.0250,26.8125,1.7625,39.8125,291.3375,0.3250,10.87375,1.4000,25.8625,1887.7750
253,2019.0,17.0,12/29/19,12,5,23,5786.0,9,21,2,...,0.0000,19.7375,1.2000,38.6125,222.3125,0.2250,11.36250,1.6125,18.2000,1774.5875
254,2019.0,17.0,12/29/19,12,28,1,5315.0,35,10,2,...,0.0125,18.7250,1.2750,40.1875,217.9625,0.2000,11.80625,1.2750,20.0125,1758.9250
255,2019.0,17.0,12/29/19,12,24,8,2850.0,21,15,2,...,0.0375,20.0750,1.2375,37.5750,230.8875,0.2500,11.54125,2.0250,19.6625,1755.3625

In [11]:
for col, col_data in df.iteritems():
    if col_data.dtype == object:
        print(col)

gameDate
gameTimeEastern
homeNickname
visitorNickname
siteCity
siteState
roofType

In [12]:
df_mapped = df_mapped.drop('gameDate', axis=1)

In [15]:
columns_not_standard = ['gameTimeEastern', 'homeNickname', 'visitorNickname',
                        'siteCity', 'siteState', 'roofType']

In [16]:
df_standard = df_mapped.drop(columns_not_standard, axis=1)
df_objects = df_mapped[columns_not_standard]

In [19]:
df_objects.head()

,gameTimeEastern,homeNickname,visitorNickname,siteCity,siteState,roofType
0,4,2,20,6,20,2
1,2,21,24,5,8,2
2,2,14,26,30,1,2
3,2,18,4,11,11,2
4,2,32,15,24,22,1

In [20]:
cols = df_standard.columns

In [23]:
scaler = preprocessing.MinMaxScaler()
df_clean_array = scaler.fit_transform(df_standard)
df_standard = pd.DataFrame(df_clean_array)

In [24]:
df_standard.columns = cols

In [25]:
df_standard.head()

,season,week,siteId,visitorTeamScore,homeTeamScore,HfirstDownsTotal,HfirstDownsByRushing,HfirstDownsByPassing,HfirstdownsByPenalty,HthirdDownAttempted,...,VpuntReturnsTouchdowns,VreceivingReceptions,VreceivingTouchdowns,VreceivingLong,VreceivingYards,VreceivingFumbles,VrecevingAverageYards,VtotalTurnovers,VtotalPointsScored,VtimeOfPossSeconds
0,0.0,0.0,0.753905,0.0,0.0,0.192884,0.435798,0.271399,0.450704,0.192771,...,0.142857,0.551481,1.000000,1.000000,0.794834,0.111111,0.813108,0.243902,0.708982,0.568260
1,0.0,0.0,0.152174,0.0,0.0,0.299625,0.836576,0.181628,0.408451,0.373494,...,0.285714,0.118477,0.180723,0.293379,0.050631,0.277778,0.432836,0.414634,0.087425,0.112908
2,0.0,0.0,0.363233,0.0,0.0,0.496255,0.762646,0.423800,0.521127,0.536145,...,0.142857,0.442877,0.445783,0.706621,0.576607,0.888889,0.606749,0.621951,0.335329,0.449090
3,0.0,0.0,0.571760,0.0,0.0,0.116105,0.626459,0.150313,0.000000,1.000000,...,0.000000,0.129760,0.240964,0.269406,0.051952,0.722222,0.312135,0.768293,0.144910,0.240037
4,0.0,0.0,0.127480,0.0,0.0,0.308989,0.533074,0.313152,0.690141,0.415663,...,0.000000,0.750353,0.783133,0.718037,0.861021,0.388889,0.541207,0.390244,0.609581,0.584306

In [26]:
df_final = pd.merge(df_objects, df_standard, left_index=True, right_index=True)

In [27]:
df_final

,gameTimeEastern,homeNickname,visitorNickname,siteCity,siteState,roofType,season,week,siteId,visitorTeamScore,...,VpuntReturnsTouchdowns,VreceivingReceptions,VreceivingTouchdowns,VreceivingLong,VreceivingYards,VreceivingFumbles,VrecevingAverageYards,VtotalTurnovers,VtotalPointsScored,VtimeOfPossSeconds
0,4,2,20,6,20,2,0.0,0.0,0.753905,0.0,...,0.142857,0.551481,1.000000,1.000000,0.794834,0.111111,0.813108,0.243902,0.708982,0.568260
1,2,21,24,5,8,2,0.0,0.0,0.152174,0.0,...,0.285714,0.118477,0.180723,0.293379,0.050631,0.277778,0.432836,0.414634,0.087425,0.112908
2,2,14,26,30,1,2,0.0,0.0,0.363233,0.0,...,0.142857,0.442877,0.445783,0.706621,0.576607,0.888889,0.606749,0.621951,0.335329,0.449090
3,2,18,4,11,11,2,0.0,0.0,0.571760,0.0,...,0.000000,0.129760,0.240964,0.269406,0.051952,0.722222,0.312135,0.768293,0.144910,0.240037
4,2,32,15,24,22,1,0.0,0.0,0.127480,0.0,...,0.000000,0.750353,0.783133,0.718037,0.861021,0.388889,0.541207,0.390244,0.609581,0.584306
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,2,4,18,29,19,2,0.0,1.0,0.574504,0.0,...,0.142857,0.000000,0.000000,0.151826,0.000000,0.111111,0.540558,0.719512,0.158084,0.557302
252,2,21,27,5,8,2,0.0,1.0,0.152174,0.0,...,0.285714,1.000000,0.783133,0.478311,1.000000,0.833333,0.155743,0.390244,0.832335,0.883765
253,12,5,23,9,21,2,0.0,1.0,1.000000,0.0,...,0.000000,0.201693,0.240964,0.368721,0.189610,0.388889,0.409474,0.597561,0.098204,0.293132
254,12,28,1,35,10,2,0.0,1.0,0.900591,0.0,...,0.142857,0.087447,0.313253,0.512557,0.138538,0.277778,0.639844,0.268293,0.271856,0.211402
255,12,24,8,21,15,2,0.0,1.0,0.380329,0.0,...,0.428571,0.239774,0.277108,0.273973,0.290285,0.500000,0.502271,1.000000,0.238323,0.192812

In [28]:
df_final.to_csv("../data/2019_averages_standized.csv", index=False)